#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

sys.path.append("../vspkgenerator")

if __name__ == '__main__':
    from vspkgenerator import generate_vsd_apidoc
    sys.exit(generate_vsd_apidoc(sys.argv))
