#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

sys.path.append("../vspkgenerator")

if __name__ == '__main__':
    from vspkgenerator import generate_vspk
    sys.exit(generate_vspk(sys.argv, prefix="vspkgenerator"))
